---
title: "2014_2015_2016_Auke_qPCR"
author: "Douglas Yu"
date: "10/05/2018"
output: html_document
---

Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(broom)
library(cowplot)
library(MASS)
library(DHARMa)
library(tidyverse)
sessionInfo()
```

```{r read in datasets and combine, eval = FALSE}
loadFile1 <- function(salmonspecies, year) { 
    filename <- str_c(salmonspecies, "long_", year, ".tsv") # Sockeyelong_2014.tsv
    foldername <- str_c(year, "_Auke_qPCR") # 2014_Auke_qPCR/
    df <- read_tsv(file.path("..", foldername, "data", filename))

    df$Year <- year # add year columnm

    df # output is df
}

years <- c("2014", "2015", "2016")
species <- c("Sockeye", "Coho")

for(year in years) 
    {
    for(salmonspecies in species) 
        {
        assign(str_c(salmonspecies, "long_", year), loadFile1(salmonspecies, year))
        }
    }

# names(Sockeyelong_2014)
# names(Sockeyelong_2015)
# names(Sockeyelong_2016)
# 
# names(Coholong_2014)
# names(Coholong_2015)
# names(Coholong_2016)

Sockeyelong_all <- bind_rows(Sockeyelong_2014, Sockeyelong_2015, Sockeyelong_2016)
Coholong_all <- bind_rows(Coholong_2014, Coholong_2015, Coholong_2016)

names(Sockeyelong_all)
names(Coholong_all)
```

```{r write files, eval = FALSE}
write_tsv(Sockeyelong_all, "Sockeyelong_all.tsv")
write_tsv(Coholong_all, "Coholong_all.tsv")
```

```{r 1 read saved files}
Sockeyelong_all <- read_tsv("Sockeyelong_all.tsv")
Sockeyelong_all$Year <- as.factor(Sockeyelong_all$Year)
Coholong_all <- read_tsv("Coholong_all.tsv")
Coholong_all$Year <- as.factor(Coholong_all$Year)

names(Sockeyelong_all)
Sockeyelong_all
names(Coholong_all)
Coholong_all
```

```{r 2 data subsets}
sockeye.adult.start = "06-18"
sockeye.adult.end = "08-01"
coho.adult.start = "08-18"  # first appearance of 1 Coho male and 1 Coho female
coho.adult.end = "10-21"  # 10-21 is last date of 

sockeye.juv.start = "04-15"
sockeye.juv.end = "06-10"
coho.juv.start = "04-15"
coho.juv.end = "06-10"

sockeye_adult <- Sockeyelong_all %>% dplyr::filter(
    (Date >= as.Date(paste0("2014-",sockeye.adult.start)) & Date <= as.Date(paste0("2014-",sockeye.adult.end)))|
    (Date >= as.Date(paste0("2015-",sockeye.adult.start)) & Date <= as.Date(paste0("2015-",sockeye.adult.end)))|
    (Date >= as.Date(paste0("2016-",sockeye.adult.start)) & Date <= as.Date(paste0("2016-",sockeye.adult.end))))

coho_adult <- Coholong_all %>% dplyr::filter(
    (Date >= as.Date(paste0("2014-",coho.adult.start)) & Date <= as.Date(paste0("2014-",coho.adult.end)))|
    (Date >= as.Date(paste0("2015-",coho.adult.start)) & Date <= as.Date(paste0("2015-",coho.adult.end)))|
    (Date >= as.Date(paste0("2016-",coho.adult.start)) & Date <= as.Date(paste0("2016-",coho.adult.end))))

sockeye_juv <- Sockeyelong_all %>% dplyr::filter(
    (Date >= as.Date(paste0("2014-",sockeye.juv.start)) & Date <= as.Date(paste0("2014-",sockeye.juv.end)))|
    (Date >= as.Date(paste0("2015-",sockeye.juv.start)) & Date <= as.Date(paste0("2015-",sockeye.juv.end)))|
    (Date >= as.Date(paste0("2016-",sockeye.juv.start)) & Date <= as.Date(paste0("2016-",sockeye.juv.end))))

coho_juv <- Coholong_all %>% dplyr::filter(
    (Date >= as.Date(paste0("2014-",coho.juv.start)) & Date <= as.Date(paste0("2014-",coho.juv.end)))|
    (Date >= as.Date(paste0("2015-",coho.juv.start)) & Date <= as.Date(paste0("2015-",coho.juv.end)))|
    (Date >= as.Date(paste0("2016-",coho.juv.start)) & Date <= as.Date(paste0("2016-",coho.juv.end))))


# calculate a single Q_cfs value from scratch
sockeye_adult <- sockeye_adult %>% mutate(Q_cfs2 = 7.48*(Gage_Height - 20.33)^2.5) # coefficients are from the excel spreadsheet:  Salmon_2015_qPCR_count_Qcfs_20180504.xlsx
plot(sockeye_adult$Gage_Height, sockeye_adult$Q_cfs)
plot(sockeye_adult$Gage_Height, sockeye_adult$Q_cfs2)

coho_adult <- coho_adult %>% mutate(Q_cfs2 = 7.48*(Gage_Height - 20.33)^2.5) # coefficients are from the excel spreadsheet:  Salmon_2015_qPCR_count_Qcfs_20180504.xlsx
plot(coho_adult$Gage_Height, coho_adult$Q_cfs)
plot(coho_adult$Gage_Height, coho_adult$Q_cfs2)
                                                   
# log(salmon) = a + b*C_t + c*log(G) + d*C_t*log(G)
# log(salmon) = a + C_t(b + d*log(G)) + c*log(G) # d corrects C_t by flow
```

Timelines
```{r 3 timelines_full fxn for long data, warning=FALSE}
timelines_full <- function(salmonspecies, start = "2015-01-01", end = "2015-12-31", type = "_adult") { # x == Sockeye, Coho, y == _adult, _juv

    salmon_use <- get(paste0(salmonspecies, type)) # Sockeye_adult or Coho_adult
    
    salmon_use <- salmon_use %>% dplyr::filter(Date >= as.Date(start) & Date <= as.Date(end))  # truncate start and stop times
    
    Salmon_type <- str_to_title(paste0(salmonspecies, "type"))

    counts <- ggplot(salmon_use, aes(Date, Count, col = get(Salmon_type))) + geom_point(size = 0.5) + geom_line() + xlab("") + ylab("Salmon Counts") + background_grid(major = "x", minor="x", size.minor = 0.5, colour.minor = "grey90") + theme(legend.position = "top")
        
    qpcrcorrQ <- ggplot(salmon_use, aes(Date, Qcorr_qPCR)) + geom_point(size = 0.5) + geom_line() + xlab("") + ylab("Qcfs*QUANT") + background_grid(major = "x", minor="x", size.minor = 0.5, colour.minor = "grey90")
        
    qpcr <- ggplot(salmon_use, aes(Date, exp(-CT_mean))) + geom_point(size = 0.5) + geom_line() + xlab("") + ylab("exp(qPCR)") + background_grid(major = "x", minor="x", size.minor = 0.5, colour.minor = "grey90")
        
    Q_cfs <- ggplot(salmon_use, aes(Date, Q_cfs)) + geom_line() + xlab("") + ylab("Q_cfs") + background_grid(major = "x", minor="x", size.minor = 0.5, colour.minor = "grey90")
    
    water <- ggplot(salmon_use, aes(Date, log(Gage_Height))) + geom_line() + xlab("") + ylab("Log(Gage Height)") + background_grid(major = "x", minor="x", size.minor = 0.5, colour.minor = "grey90")
    
    temp <- ggplot(salmon_use, aes(Date, Temp_C)) + geom_line() + xlab("") + ylab("Temp_C") + background_grid(major = "x", minor="x", size.minor = 0.5, colour.minor = "grey90")
    
    plot_grid(counts, qpcrcorrQ, qpcr, Q_cfs, water, temp, nrow = 6, align = "v")
}
```

```{r 4 timelines_full usage}
timelines_full("sockeye") # use sockeye, not Sockeye 
timelines_full("sockeye", "2015-06-18", "2015-08-01") # after looking at the full timeline, truncating to 01 Aug to prevent measuring dead-salmon DNA in 2016
timelines_full("sockeye", "2015-04-15", "2015-06-10", "_juv") # downstream weir dates only for smolts
timelines_full("coho") # use coho, not Coho
timelines_full("coho", "2015-06-18", "2015-10-30") # after looking at the full timeline
timelines_full("coho", "2015-04-15", "2015-06-10", "_juv") # downstream weir dates only 
```

Sockeye models
```{r linear model}
# 2015 data
datasubset = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2015")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

sockeye.adult.2015.reg <- lm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset) 
summary(sockeye.adult.2015.reg)

# estimate residuals with DHARMa
plotConventionalResiduals(sockeye.adult.2015.reg)
simulationOutput <- simulateResiduals(fittedModel = sockeye.adult.2015.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T) # are uniform except for lowest predicted values
testUniformity(simulationOutput) # p = 0.375, D = 0.212, overdispersaion ns

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C,  simulationOutput$scaledResiduals) # a bit of overdispersion
plotResiduals(datasubset$QUANT_mean,  simulationOutput$scaledResiduals) # uniform
plotResiduals(datasubset$Q_cfs2,  simulationOutput$scaledResiduals) # a bit of heteroscedastic:  higher Q_cfs leads to more model underestimates
plotResiduals(datasubset$QUANTQ,  simulationOutput$scaledResiduals) # underdispersed. higher QUANTQ 
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 0.186, DW = 1.57, temp autocorr ns (although the plot shows that residuals increase over time)
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.338 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# sockeye.adult.2015.reg <- lm(Count ~ QUANT_mean:Q_cfs2, data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2015"))
# summary(sockeye.adult.2015.reg)

# 2016 data
datasubset = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2016")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

sockeye.adult.2016.reg <- lm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2016"))
summary(sockeye.adult.2016.reg)

# estimate residuals with DHARMa
plotConventionalResiduals(sockeye.adult.2016.reg)
simulationOutput <- simulateResiduals(fittedModel = sockeye.adult.2016.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T) # overdispersed and non-normal residuals
testUniformity(simulationOutput) # p = 0.0005, D = 0.326, overdispersaion highly sig

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C,  simulationOutput$scaledResiduals) # a bit of overdispersion
plotResiduals(datasubset$QUANT_mean,  simulationOutput$scaledResiduals) # a bit of overdispersion
plotResiduals(datasubset$Q_cfs2,  simulationOutput$scaledResiduals) # underdispersed
plotResiduals(datasubset$QUANTQ,  simulationOutput$scaledResiduals) # this is the source of the overdispersion
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 0.035, DW = 1.43, temp autocorr ns (although the plot shows that residuals increase over time)
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.962 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

tidy(sockeye.adult.2015.reg)
tidy(sockeye.adult.2016.reg)

# sockeye.adult.2016.reg <- lm(Count ~ QUANT_mean:Q_cfs2, data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2016"))
# summary(sockeye.adult.2016.reg)

# 2015 & 2016 data:   with Year interaction term.  year interaction is not sig, which is nice
datasubset = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

sockeye.adult.reg <- lm((Count) ~ QUANT_mean:Q_cfs2*Year+Temp_C, data = datasubset)
summary(sockeye.adult.reg)

simulationOutput <- simulateResiduals(fittedModel = sockeye.adult.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T) # overdispersed and non-normal residuals
testUniformity(simulationOutput) # p = 0.002, D = 0.252, overdispersaion highly sig

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C,  simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$QUANT_mean,  simulationOutput$scaledResiduals) # a bit of overdispersion
plotResiduals(datasubset$Q_cfs2,  simulationOutput$scaledResiduals) # a bit of overdispersion
plotResiduals(datasubset$QUANTQ,  simulationOutput$scaledResiduals) # a bit of overdispersion
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 0.005, DW = 1.32, temp autocorr 
testTemporalAutocorrelation(simulationOutput = simulationOutput, plot = T) # p = 0.494 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# conventional residuals for linear models
plotConventionalResiduals(sockeye.adult.reg)

par(mfrow=c(2,2))
plot(sockeye.adult.reg)
par(mfrow=c(1,1))
glance(sockeye.adult.reg)

# augment(sockeye.adult.reg)
# 
# #plot2016
# par(mfrow=c(2,1))
# plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], type='l')
# 
# lines(datasubset$Date[which(datasubset$Year==2016)], (predict(sockeye.adult.reg))[which(datasubset$Year==2016)], lty=2, col="blue")
# 
# #plot 2015
# plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], type='l')
# 
# lines(datasubset$Date[which(datasubset$Year==2015)], (predict(sockeye.adult.reg))[which(datasubset$Year==2015)], lty=2, col="blue")
# par(mfrow=c(1,1))
# 
# #2015 total and predicted salmon
# sum((predict(sockeye.adult.reg))[which(datasubset$Year==2015)])
# sum(datasubset$Count[which(datasubset$Year==2015)])
# 
# #2016 total and predicted salmon
# sum((predict(sockeye.adult.reg))[which(datasubset$Year==2016)])
# sum(datasubset$Count[which(datasubset$Year==2016)])
```

```{r plot 2015 sockeye for gaussian}
par(mfrow=c(2,1),mar=c(2,3,1,1),oma=c(1,3,1,1))

plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], lwd=2, type='n',pch=19,cex=0.25,ylim=c(0,800),ylab="",xlab="",cex.lab=1.5)

y_up=augment(sockeye.adult.reg)$.fitted[which(datasubset$Year==2015)] + 2*augment(sockeye.adult.reg)$.se.fit[which(datasubset$Year==2015)]
 
y_down=augment(sockeye.adult.reg)$.fitted[which(datasubset$Year==2015)] - 2*augment(sockeye.adult.reg)$.se.fit[which(datasubset$Year==2015)]

polygon(c(rev(datasubset$Date[which(datasubset$Year==2015)]),datasubset$Date[which(datasubset$Year==2015)]),c(rev(y_up),y_down),col="grey80",border=NA)

points(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], lwd=2, type='b',pch=19,cex=0.25)

lines(datasubset$Date[which(datasubset$Year==2015)], augment(sockeye.adult.reg)$.fitted[which(datasubset$Year==2015)], lwd=2,lty=2, col="blue")
text(datasubset$Date[which(datasubset$Year==2015)][15],750,"2015",cex=1.5) 
 
``` 

```{r plot 2016 sockeye for gaussian}
plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], lwd=2, type='n',pch=19,cex=0.25,ylim=c(0,800),ylab="",xlab="",cex.lab=1.5)

y_up=augment(sockeye.adult.reg)$.fitted[which(datasubset$Year==2016)] + 2*augment(sockeye.adult.reg)$.se.fit[which(datasubset$Year==2016)]
 
y_down=augment(sockeye.adult.reg)$.fitted[which(datasubset$Year==2016)] - 2*augment(sockeye.adult.reg)$.se.fit[which(datasubset$Year==2016)]

polygon(c(rev(datasubset$Date[which(datasubset$Year==2016)]),datasubset$Date[which(datasubset$Year==2016)]),c(rev(y_up),y_down),col="grey80",border=NA)

points(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], lwd=2, type='b',pch=19,cex=0.25)

lines(datasubset$Date[which(datasubset$Year==2016)], augment(sockeye.adult.reg)$.fitted[which(datasubset$Year==2016)], lwd=2,lty=2, col="blue")
mtext("Sockeye Counts Gaussian model",side=2,cex=2,outer=T)
text(datasubset$Date[which(datasubset$Year==2016)][37],750,"2016",cex=1.5)


#2015 total and predicted salmon
sum(predict(sockeye.adult.reg)[which(datasubset$Year==2015)])
sum(datasubset$Count[which(datasubset$Year==2015)])

#2016 total and predicted salmon
sum(predict(sockeye.adult.reg)[which(datasubset$Year==2016)])
sum(datasubset$Count[which(datasubset$Year==2016)])
```

```{r fit 2016 gaussian model and apply to 2015}
# 2016 data and model
datasubset = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

sockeye.adult.2016.reg <- lm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset[datasubset$Year == "2016", ])
summary(sockeye.adult.2016.reg)
tidy(sockeye.adult.2016.reg)
#                term estimate std.error statistic      p.value
# 1       (Intercept) 293.1952 207.54274  1.412698 1.663320e-01
# 2            Temp_C -16.5771  12.12875 -1.366761 1.801758e-01
# 3 QUANT_mean:Q_cfs2 520.7783  72.24677  7.208326 1.753041e-08
coef(sockeye.adult.2016.reg)[1] # intercept
coef(sockeye.adult.2016.reg)[2] # Temp_C
coef(sockeye.adult.2016.reg)[3] # QUANT_mean:Q_cfs

# 2015 data and model
sockeye.adult.2015.reg <- lm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset[datasubset$Year == "2015", ])
summary(sockeye.adult.2015.reg)
tidy(sockeye.adult.2015.reg)
#                term  estimate std.error statistic    p.value
# 1       (Intercept) 693.60927 289.71226  2.394132 0.03243932
# 2            Temp_C -39.40804  17.08566 -2.306499 0.03819533
# 3 QUANT_mean:Q_cfs2 885.76286 236.96014  3.738025 0.00248345
coef(sockeye.adult.2015.reg)[1] # intercept
coef(sockeye.adult.2015.reg)[2] # Temp_C
coef(sockeye.adult.2015.reg)[3] # QUANT_mean:Q_cfs


par(mfrow=c(2,1))
#plot2016
plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], type='l', ylim=c(0,600))
lines(datasubset$Date[which(datasubset$Year==2016)], predict(sockeye.adult.2016.reg), lty=2, col="black")
text(datasubset$Date[which(datasubset$Year==2016)][35],550,"2016",cex=1.5) 

#plot 2015 with 2016 model
plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], type='l', ylim=c(0,600))

lines(datasubset$Date[which(datasubset$Year==2015)], 
    coef(sockeye.adult.2016.reg)[1] + 
    coef(sockeye.adult.2016.reg)[2] * datasubset$Temp_C[which(datasubset$Year==2015)] +
    coef(sockeye.adult.2016.reg)[3] * datasubset$QUANT_mean[which(datasubset$Year==2015)] * datasubset$Q_cfs2[which(datasubset$Year==2015)], lty=2, col="black")
lines(datasubset$Date[which(datasubset$Year==2015)], 
    coef(sockeye.adult.2015.reg)[1] + 
    coef(sockeye.adult.2015.reg)[2] * datasubset$Temp_C[which(datasubset$Year==2015)] +
    coef(sockeye.adult.2015.reg)[3] * datasubset$QUANT_mean[which(datasubset$Year==2015)] * datasubset$Q_cfs2[which(datasubset$Year==2015)], lty=2, col="blue")
text(datasubset$Date[which(datasubset$Year==2015)][14.5],550,"2015",cex=1.5) 
par(mfrow=c(1,1))

#2015 total and predicted salmon
sum(predict(sockeye.adult.2015.reg))
sum(datasubset$Count[which(datasubset$Year==2015)])

#2016 total and predicted salmon
sum(predict(sockeye.adult.2016.reg))
sum(datasubset$Count[which(datasubset$Year==2016)])

```

Question:   how does the poisson model's log link deal with 0 values?
```{r quasipoisson model}
sockeye.adult.2015.reg <- glm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, family = "quasipoisson", data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2015")) 
summary(sockeye.adult.2015.reg) 

# sockeye.adult.2015.reg <- glm(Count ~ QUANT_mean:Q_cfs2, family = "quasipoisson", data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2015"))
# summary(sockeye.adult.2015.reg)

sockeye.adult.2016.reg <- glm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, family = "quasipoisson", data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2016"))
summary(sockeye.adult.2016.reg)

# sockeye.adult.2016.reg <- glm(Count ~ QUANT_mean:Q_cfs2, family = "quasipoisson", data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2016"))
# summary(sockeye.adult.2016.reg)

tidy(sockeye.adult.2015.reg)
tidy(sockeye.adult.2016.reg)

# quasipoisson model with year interaction term
# year interaction is not sig, which is nice
datasubset = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))

sockeye.adult.reg <- glm(Count ~ QUANT_mean:Q_cfs2*Year+Temp_C, family = "quasipoisson", data = datasubset)
summary(sockeye.adult.reg)
tidy(sockeye.adult.reg)
# augment(sockeye.adult.reg)

# testing lagged terms
# sockeye.adult.reg <- glm(I(QUANT_mean*Q_cfs2)[3:39] ~ Count[1:37] +Count[2:38]+ Temp_C[3:39], family = "quasipoisson", data = datasubset[datasubset$Year==2016,])
# 
# sockeye.adult.reg <- glm(I(QUANT_mean*Q_cfs2)[2:39] ~ Count[1:38] + Temp_C[2:39], family = "quasipoisson", data = datasubset[datasubset$Year==2016,])
# summary(sockeye.adult.reg)
# augment(sockeye.adult.reg)

```

```{r fit 2016 quasipoisson model and apply to 2015}
# 2016 data and model
datasubset = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

sockeye.adult.2016.reg <- glm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, family = "quasipoisson", data = datasubset[datasubset$Year == "2016", ])
summary(sockeye.adult.2016.reg)
tidy(sockeye.adult.2016.reg)
#                term   estimate std.error statistic      p.value
# 1       (Intercept)  9.3130964 3.3091108  2.814380 7.872958e-03
# 2            Temp_C -0.3771362 0.2010814 -1.875540 6.884682e-02
# 3 QUANT_mean:Q_cfs2  4.1901427 0.7615046  5.502452 3.214462e-06
coef(sockeye.adult.2016.reg)[1] # intercept
coef(sockeye.adult.2016.reg)[2] # Temp_C
coef(sockeye.adult.2016.reg)[3] # QUANT_mean:Q_cfs

# 2015 data and model
sockeye.adult.2015.reg <- glm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, family = "quasipoisson", data = datasubset[datasubset$Year == "2015", ])
summary(sockeye.adult.2015.reg)
tidy(sockeye.adult.2015.reg)
#                term   estimate std.error statistic     p.value
# 1       (Intercept) 11.1338497 2.8339207  3.928780 0.001729471
# 2            Temp_C -0.4302193 0.1817033 -2.367702 0.034081888
# 3 QUANT_mean:Q_cfs2  4.5291445 1.4740212  3.072645 0.008903408
coef(sockeye.adult.2015.reg)[1] # intercept
coef(sockeye.adult.2015.reg)[2] # Temp_C
coef(sockeye.adult.2015.reg)[3] # QUANT_mean:Q_cfs


par(mfrow=c(2,1))
#plot2016
plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], type='l', ylim=c(0,600))
lines(datasubset$Date[which(datasubset$Year==2016)], exp(predict(sockeye.adult.2016.reg)), lty=2, col="black")
text(datasubset$Date[which(datasubset$Year==2016)][35],550,"2016",cex=1.5) 

#plot 2015 with 2016 model
plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], type='l', ylim=c(0,600))

lines(datasubset$Date[which(datasubset$Year==2015)], 
    exp(coef(sockeye.adult.2016.reg)[1] + 
    coef(sockeye.adult.2016.reg)[2] * datasubset$Temp_C[which(datasubset$Year==2015)] +
    coef(sockeye.adult.2016.reg)[3] * datasubset$QUANT_mean[which(datasubset$Year==2015)] * datasubset$Q_cfs2[which(datasubset$Year==2015)]), lty=2, col="black")
lines(datasubset$Date[which(datasubset$Year==2015)], 
    exp(coef(sockeye.adult.2015.reg)[1] + 
    coef(sockeye.adult.2015.reg)[2] * datasubset$Temp_C[which(datasubset$Year==2015)] +
    coef(sockeye.adult.2015.reg)[3] * datasubset$QUANT_mean[which(datasubset$Year==2015)] * datasubset$Q_cfs2[which(datasubset$Year==2015)]), lty=2, col="blue")
text(datasubset$Date[which(datasubset$Year==2015)][14.5],550,"2015",cex=1.5) 
par(mfrow=c(1,1))

#2015 total and predicted salmon
sum(exp(predict(sockeye.adult.2015.reg)))
sum(datasubset$Count[which(datasubset$Year==2015)])

#2016 total and predicted salmon
sum(exp(predict(sockeye.adult.2016.reg)))
sum(datasubset$Count[which(datasubset$Year==2016)])

```

```{r negative binomial model}
# library(MASS) # note that MASS::select collides with dplyr::select
# library(DHARMa)

# 2015 
datasubset = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2015") 
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

sockeye.adult.2015.reg <- glm.nb((Count+1) ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset) # count + 1 because there's a log link
summary(sockeye.adult.2015.reg) # Temp_C and QUANT*Qcfs both sig

# estimate residuals with DHARMa
simulationOutput <- simulateResiduals(fittedModel = sockeye.adult.2015.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T) # residuals look underdispersed. This leads to overwide CIs and p-values too small (so we should be more wary of concluding non-significance of a variable)
testUniformity(simulationOutput) # p = 0.683, D = 0.17, underoverdispersaion ns
# testOverdispersion(simulationOutput)  # p = 0.704, dispersion = 0.848, too conservative a test but the parametric version doesn't work for this kind of model
testZeroInflation(simulationOutput)  # p = 0.488, ratioObsExp = 0

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C,  simulationOutput$scaledResiduals) # a bit of overdispersion
plotResiduals(datasubset$QUANT_mean,  simulationOutput$scaledResiduals) # uniform
plotResiduals(datasubset$Q_cfs2,  simulationOutput$scaledResiduals) # a bit of heteroscedastic:  higher Q_cfs leads to more model underestimates
plotResiduals(datasubset$QUANTQ,  simulationOutput$scaledResiduals) # underdispersed. higher QUANTQ 
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 0.367, DW = 1.83, temp autocorr ns (although the plot shows that residuals increase over time)
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.523 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# sockeye.adult.2015.reg <- glm.nb((Count+1) ~ QUANT_mean:Q_cfs2, data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2015")) # count + 1 because there's a log link
# summary(sockeye.adult.2015.reg)
# simulationOutput <- simulateResiduals(fittedModel = sockeye.adult.2015.reg, n = 1000)
# plotSimulatedResiduals(simulationOutput = simulationOutput) # residuals worse than model without Temp_C

# 2016
datasubset = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2016")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

# DHARMa residuals
sockeye.adult.2016.reg <- glm.nb((Count + 1) ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset) # count + 1 because there's a log link
summary(sockeye.adult.2016.reg)
simulationOutput <- simulateResiduals(fittedModel = sockeye.adult.2016.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput) # very few data at high predicted values, but at low predicted values, residuals are nicely uniformly distributed. # we could say that residuals are a bit underdispersed. This leads to overwide CIs and p-values too small (so we should be more wary of concluding non-significance of a variable)
testUniformity(simulationOutput) # p = 0.683, D = 0.17, underoverdispersaion ns
# testOverdispersion(simulationOutput)  # p = 0.704, dispersion = 0.848, too conservative a test but the parametric version doesn't work for this kind of model
testZeroInflation(simulationOutput)  # p = 0.488, ratioObsExp = 0

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C, simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$QUANT_mean, simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$Q_cfs2, simulationOutput$scaledResiduals) # a bit heteroscedastic:  higher Q_cfs leads to more model underestimates
plotResiduals(datasubset$QUANTQ, simulationOutput$scaledResiduals) # basically uniform
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 0.0046, DW = 1.21, temp autocorr very sig:  more positive residuals later, so should I truncate the time series a bit?  and if so, where?
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.886 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# sockeye.adult.2016.reg <- glm.nb((Count + 1) ~ QUANT_mean:Q_cfs2, data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2016")) # count + 1 because there's a log link
# summary(sockeye.adult.2016.reg)
# simulationOutput <- simulateResiduals(fittedModel = sockeye.adult.2016.reg, n = 1000)
# plotSimulatedResiduals(simulationOutput = simulationOutput)

tidy(sockeye.adult.2015.reg)
tidy(sockeye.adult.2016.reg)

# negative binomial model with year interaction term
# year interaction is not sig, which is nice
datasubset = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

sockeye.adult.reg <- glm.nb((Count + 1) ~ QUANT_mean:Q_cfs2*Year + Temp_C, data = datasubset) # count + 1 because there's a log link
summary(sockeye.adult.reg)
tidy(sockeye.adult.reg)
# augment(sockeye.adult.reg)

# DHARMa residuals
simulationOutput <- simulateResiduals(fittedModel = sockeye.adult.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput) # very few data at high predicted values, but at the low predicted values, residuals are nicely uniformly distributed. # we could say that residuals are a bit underdispersed. This leads to overwide CIs and p-values too small (so we should be more wary of concluding non-significance of a variable)
testUniformity(simulationOutput) # p = 0.083, D = 0.170, underoverdispersaion ns
# testOverdispersion(simulationOutput)  # p = 0.704, dispersion = 0.848, too conservative a test but the parametric version doesn't work for this kind of model
testZeroInflation(simulationOutput)  # p = 1, ratioObsExp = 0

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C, simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$QUANT_mean, simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$Q_cfs2, simulationOutput$scaledResiduals) # underdispersed
plotResiduals(datasubset$QUANTQ, simulationOutput$scaledResiduals) # underdispersed
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 0.025, DW = 1.48, temp autocorr very sig:  more positive residuals later, so should I truncate the time series a bit?  and if so, where?
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.686, DW = 2.13 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# testing lagged terms
# sockeye.adult.reg <- glm(I(QUANT_mean*Q_cfs2)[3:39] ~ Count[1:37] +Count[2:38]+ Temp_C[3:39], family = "quasipoisson", data = datasubset[datasubset$Year==2016,])
# 
# sockeye.adult.reg <- glm(I(QUANT_mean*Q_cfs2)[2:39] ~ Count[1:38] + Temp_C[2:39], family = "quasipoisson", data = datasubset[datasubset$Year==2016,])
# summary(sockeye.adult.reg)
# augment(sockeye.adult.reg)

``` 

```{r fit 2016 negative binomial model and apply to 2015}
# 2016 data and model
datasubset = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

sockeye.adult.2016.reg <- glm.nb((Count+1) ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset[datasubset$Year == "2016", ])
summary(sockeye.adult.2016.reg)
tidy(sockeye.adult.2016.reg)
#                term   estimate std.error statistic      p.value
# 1       (Intercept)  8.9590161 3.2681441  2.741316 6.119360e-03
# 2            Temp_C -0.3999765 0.1913104 -2.090720 3.655317e-02
# 3 QUANT_mean:Q_cfs2  7.8867279 1.1213802  7.033054 2.020610e-12
coef(sockeye.adult.2016.reg)[1] # intercept
coef(sockeye.adult.2016.reg)[2] # Temp_C
coef(sockeye.adult.2016.reg)[3] # QUANT_mean:Q_cfs

# 2015 data and model
sockeye.adult.2015.reg <- glm.nb((Count+1) ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset[datasubset$Year == "2015", ])
summary(sockeye.adult.2015.reg)
tidy(sockeye.adult.2015.reg)
#                term   estimate std.error statistic      p.value
# 1       (Intercept) 16.1428216 3.3679066  4.793132 1.641973e-06
# 2            Temp_C -0.7615229 0.1991564 -3.823744 1.314406e-04
# 3 QUANT_mean:Q_cfs2  6.4566453 2.7295963  2.365421 1.800957e-02
coef(sockeye.adult.2015.reg)[1] # intercept
coef(sockeye.adult.2015.reg)[2] # Temp_C
coef(sockeye.adult.2015.reg)[3] # QUANT_mean:Q_cfs


par(mfrow=c(2,1))
#plot2016
plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], type='l', ylim=c(0,600))
lines(datasubset$Date[which(datasubset$Year==2016)], exp(predict(sockeye.adult.2016.reg)), lty=2, col="black")
text(datasubset$Date[which(datasubset$Year==2016)][35],550,"2016",cex=1.5) 

#plot 2015 with 2016 model
plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], type='l', ylim=c(0,600))

lines(datasubset$Date[which(datasubset$Year==2015)], 
    exp(coef(sockeye.adult.2016.reg)[1] + 
    coef(sockeye.adult.2016.reg)[2] * datasubset$Temp_C[which(datasubset$Year==2015)] +
    coef(sockeye.adult.2016.reg)[3] * datasubset$QUANT_mean[which(datasubset$Year==2015)] * datasubset$Q_cfs2[which(datasubset$Year==2015)]), lty=2, col="black")
lines(datasubset$Date[which(datasubset$Year==2015)], 
    exp(coef(sockeye.adult.2015.reg)[1] + 
    coef(sockeye.adult.2015.reg)[2] * datasubset$Temp_C[which(datasubset$Year==2015)] +
    coef(sockeye.adult.2015.reg)[3] * datasubset$QUANT_mean[which(datasubset$Year==2015)] * datasubset$Q_cfs2[which(datasubset$Year==2015)]), lty=2, col="blue")
text(datasubset$Date[which(datasubset$Year==2015)][14.5],550,"2015",cex=1.5) 
par(mfrow=c(1,1))

#2015 total and predicted salmon
sum(exp(predict(sockeye.adult.2015.reg)))
sum(datasubset$Count[which(datasubset$Year==2015)])

#2016 total and predicted salmon
sum(exp(predict(sockeye.adult.2016.reg)))
sum(datasubset$Count[which(datasubset$Year==2016)])

```

```{r plot 2015 sockeye for negbin and poisson}
par(mfrow=c(2,1),mar=c(2,3,1,1),oma=c(1,3,1,1))
 
plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], lwd=2, type='n',pch=19,cex=0.25,ylim=c(0,800),ylab="",xlab="",cex.lab=1.5)

y_up=exp(augment(sockeye.adult.reg)$.fitted + 2*augment(sockeye.adult.reg)$.se.fit)[which(datasubset$Year==2015)]
 
y_down=exp(augment(sockeye.adult.reg)$.fitted - 2*augment(sockeye.adult.reg)$.se.fit)[which(datasubset$Year==2015)]

polygon(c(rev(datasubset$Date[which(datasubset$Year==2015)]),datasubset$Date[which(datasubset$Year==2015)]),c(rev(y_up),y_down),col="grey80",border=NA)

points(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], lwd=2, type='b',pch=19,cex=0.25)

lines(datasubset$Date[which(datasubset$Year==2015)], exp(augment(sockeye.adult.reg)$.fitted)[which(datasubset$Year==2015)], lwd=2,lty=2, col="blue")
text(datasubset$Date[which(datasubset$Year==2015)][15],750,"2015",cex=1.5) 
 
```

```{r plot 2016 sockeye for negbin and poisson}
plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], lwd=2, type='n',pch=19,cex=0.25,ylim=c(0,1600),ylab="",xlab="",cex.lab=1.5)

y_up=exp(augment(sockeye.adult.reg)$.fitted + 2*augment(sockeye.adult.reg)$.se.fit)[which(datasubset$Year==2016)]
 
y_down=exp(augment(sockeye.adult.reg)$.fitted - 2*augment(sockeye.adult.reg)$.se.fit)[which(datasubset$Year==2016)]

polygon(c(rev(datasubset$Date[which(datasubset$Year==2016)]),datasubset$Date[which(datasubset$Year==2016)]),c(rev(y_up),y_down),col="grey80",border=NA)

points(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], lwd=2, type='b',pch=19,cex=0.25)

lines(datasubset$Date[which(datasubset$Year==2016)], exp(augment(sockeye.adult.reg)$.fitted)[which(datasubset$Year==2016)], lwd=2,lty=2, col="blue")
mtext("Sockeye Counts Negative binomial model",side=2,cex=2,outer=T)
text(datasubset$Date[which(datasubset$Year==2016)][37],1500,"2016",cex=1.5)
# 
# lines(datasubset$Date[which(datasubset$Year==2016)], exp(augment(sockeye.adult.reg)$.fitted + 2*augment(sockeye.adult.reg)$.se.fit)[which(datasubset$Year==2016)], lwd=2,lty=3, col="darkgray")
# 
# lines(datasubset$Date[which(datasubset$Year==2016)], exp(augment(sockeye.adult.reg)$.fitted - 2*augment(sockeye.adult.reg)$.se.fit)[which(datasubset$Year==2016)], lwd=2,lty=3, col="darkgray")

# plot 2015
# plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], type='b',pch=19,cex=0.25,ylim=c(0,800),lwd=2,ylab="Sockeye Counts",xlab="")
# 
# #add confint augment(sockeye.adult.reg)
# lines(datasubset$Date[which(datasubset$Year==2015)], exp(augment(sockeye.adult.reg)$.fitted)[which(datasubset$Year==2015)], lwd=2,lty=2, col="blue")
# 
# lines(datasubset$Date[which(datasubset$Year==2015)], exp(augment(sockeye.adult.reg)$.fitted + 2*augment(sockeye.adult.reg)$.se.fit)[which(datasubset$Year==2015)], lwd=2,lty=3, col="darkgray")
# 
# lines(datasubset$Date[which(datasubset$Year==2015)], exp(augment(sockeye.adult.reg)$.fitted - 2*augment(sockeye.adult.reg)$.se.fit)[which(datasubset$Year==2015)], lwd=2,lty=3, col="darkgray")


#2015 total and predicted salmon
sum(exp(predict(sockeye.adult.reg))[which(datasubset$Year==2015)])
sum(datasubset$Count[which(datasubset$Year==2015)])

#2016 total and predicted salmon
sum(exp(predict(sockeye.adult.reg))[which(datasubset$Year==2016)])
sum(datasubset$Count[which(datasubset$Year==2016)])
```


Coho_adult models
```{r linear model}
# 2015 data
datasubset = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2015")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2015.reg <- lm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset) 
summary(coho.adult.2015.reg)

# estimate residuals with DHARMa
plotConventionalResiduals(coho.adult.2015.reg)
simulationOutput <- simulateResiduals(fittedModel = coho.adult.2015.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T) # are uniform except for lowest predicted values
testUniformity(simulationOutput) # p = 0.282, D = 0.141, overdispersaion ns

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C,  simulationOutput$scaledResiduals) # uniform
plotResiduals(datasubset$QUANT_mean,  simulationOutput$scaledResiduals) # a bit heteroscedastic
plotResiduals(datasubset$Q_cfs2,  simulationOutput$scaledResiduals) # a bit heteroscedastic
plotResiduals(datasubset$QUANTQ,  simulationOutput$scaledResiduals) # basically uniform to a bit overdispersed
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 0.001, DW = 1.17, temp autocorr sig, later residuals more likely to be positive
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.304 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# coho.adult.2015.reg <- lm(Count ~ QUANT_mean:Q_cfs2, data = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2015"))
# summary(coho.adult.2015.reg)

# 2016 data
datasubset = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2016")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2016.reg <- lm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, data = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2016"))
summary(coho.adult.2016.reg)

# estimate residuals with DHARMa
plotConventionalResiduals(coho.adult.2016.reg)
simulationOutput <- simulateResiduals(fittedModel = coho.adult.2016.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T) # overdispersed and non-normal residuals
testUniformity(simulationOutput) # p = 0.0006, D = 0.279, overdispersaion highly sig

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C,  simulationOutput$scaledResiduals) # heteroscedastic
plotResiduals(datasubset$QUANT_mean,  simulationOutput$scaledResiduals) # heteroscedastic
plotResiduals(datasubset$Q_cfs2,  simulationOutput$scaledResiduals) # heteroscedastic
plotResiduals(datasubset$QUANTQ,  simulationOutput$scaledResiduals) # heteroscedastic
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 2.685e-07, DW = 0.767, temp autocorr highly sig, later residuals are positive
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.794 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

tidy(coho.adult.2015.reg)
tidy(coho.adult.2016.reg)

# coho.adult.2016.reg <- lm(Count ~ QUANT_mean:Q_cfs2, data = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2016"))
# summary(coho.adult.2016.reg)

# 2015 & 2016 data:   with Year interaction term.  year interaction is not sig, which is nice
datasubset = subset(coho_adult, Cohotype == "Coho_Adults" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.reg <- lm((Count) ~ QUANT_mean:Q_cfs2*Year+Temp_C, data = datasubset)
summary(coho.adult.reg)

simulationOutput <- simulateResiduals(fittedModel = coho.adult.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T) # overdispersed and non-normal residuals
testUniformity(simulationOutput) # p = 0.001, D = 0.192, overdispersaion highly sig

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C,  simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$QUANT_mean,  simulationOutput$scaledResiduals) # a bit of overdispersion
plotResiduals(datasubset$Q_cfs2,  simulationOutput$scaledResiduals) # a bit of overdispersion
plotResiduals(datasubset$QUANTQ,  simulationOutput$scaledResiduals) # a bit of overdispersion
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 6.242e-07, DW = 1.045, temp autocorr, 2016 is driving this 
testTemporalAutocorrelation(simulationOutput = simulationOutput, plot = T) # p = 0.5411 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# conventional residuals for linear models
plotConventionalResiduals(coho.adult.reg)

par(mfrow=c(2,2))
plot(coho.adult.reg)
par(mfrow=c(1,1))
glance(coho.adult.reg)

# augment(coho.adult.reg)
# 
# #plot2016
# par(mfrow=c(2,1))
# plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], type='l')
# 
# lines(datasubset$Date[which(datasubset$Year==2016)], (predict(coho.adult.reg))[which(datasubset$Year==2016)], lty=2, col="blue")
# 
# #plot 2015
# plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], type='l')
# 
# lines(datasubset$Date[which(datasubset$Year==2015)], (predict(coho.adult.reg))[which(datasubset$Year==2015)], lty=2, col="blue")
# par(mfrow=c(1,1))
# 
# #2015 total and predicted salmon
# sum((predict(coho.adult.reg))[which(datasubset$Year==2015)])
# sum(datasubset$Count[which(datasubset$Year==2015)])
# 
# #2016 total and predicted salmon
# sum((predict(coho.adult.reg))[which(datasubset$Year==2016)])
# sum(datasubset$Count[which(datasubset$Year==2016)])
```

```{r fit 2016 gaussian model and apply to 2015}
# 2016 data and model
datasubset = subset(coho_adult, Cohotype == "Coho_Adults" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2016.reg <- lm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset[datasubset$Year == "2016", ])
summary(coho.adult.2016.reg)
tidy(coho.adult.2016.reg)
#                term   estimate  std.error statistic    p.value
# 1       (Intercept) -6.7452178  6.3650680 -1.059724 0.29446594
# 2            Temp_C  0.5311073  0.4327921  1.227165 0.22562409
# 3 QUANT_mean:Q_cfs2 83.5663613 33.6355552  2.484465 0.01643991
coef(coho.adult.2016.reg)[1] # intercept
coef(coho.adult.2016.reg)[2] # Temp_C
coef(coho.adult.2016.reg)[3] # QUANT_mean:Q_cfs

# 2015 data and model
coho.adult.2015.reg <- lm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset[datasubset$Year == "2015", ])
summary(coho.adult.2015.reg)
tidy(coho.adult.2015.reg)
#                term   estimate  std.error statistic      p.value
# 1       (Intercept) -18.338699  8.6245845 -2.126328 3.887345e-02
# 2            Temp_C   1.662789  0.7724218  2.152696 3.662184e-02
# 3 QUANT_mean:Q_cfs2 157.460512 17.2714460  9.116811 7.076874e-12
coef(coho.adult.2015.reg)[1] # intercept
coef(coho.adult.2015.reg)[2] # Temp_C
coef(coho.adult.2015.reg)[3] # QUANT_mean:Q_cfs


par(mfrow=c(2,1))
#plot2016
plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], type='l', ylim=c(0,100))
lines(datasubset$Date[which(datasubset$Year==2016)], predict(coho.adult.2016.reg), lty=2, col="black")
text(datasubset$Date[which(datasubset$Year==2016)][45],90,"2016",cex=1.5) 

#plot 2015 with 2016 model
plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], type='l', ylim=c(0,100))

lines(datasubset$Date[which(datasubset$Year==2015)], 
    coef(coho.adult.2016.reg)[1] + 
    coef(coho.adult.2016.reg)[2] * datasubset$Temp_C[which(datasubset$Year==2015)] +
    coef(coho.adult.2016.reg)[3] * datasubset$QUANT_mean[which(datasubset$Year==2015)] * datasubset$Q_cfs2[which(datasubset$Year==2015)], lty=2, col="black")
lines(datasubset$Date[which(datasubset$Year==2015)], 
    coef(coho.adult.2015.reg)[1] + 
    coef(coho.adult.2015.reg)[2] * datasubset$Temp_C[which(datasubset$Year==2015)] +
    coef(coho.adult.2015.reg)[3] * datasubset$QUANT_mean[which(datasubset$Year==2015)] * datasubset$Q_cfs2[which(datasubset$Year==2015)], lty=2, col="blue")
text(datasubset$Date[which(datasubset$Year==2015)][45],90,"2015",cex=1.5) 
par(mfrow=c(1,1))

#2015 total and predicted salmon
sum(predict(coho.adult.2015.reg))
sum(datasubset$Count[which(datasubset$Year==2015)])

#2016 total and predicted salmon
sum(predict(coho.adult.2016.reg))
sum(datasubset$Count[which(datasubset$Year==2016)])

```

```{r plot 2015 coho for gaussian}
par(mfrow=c(2,1),mar=c(2,3,1,1),oma=c(1,3,1,1))

plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], lwd=2, type='n',pch=19,cex=0.25,ylim=c(0,150),ylab="",xlab="",cex.lab=1.5)

y_up=augment(coho.adult.reg)$.fitted[which(datasubset$Year==2015)] + 2*augment(coho.adult.reg)$.se.fit[which(datasubset$Year==2015)]
 
y_down=augment(coho.adult.reg)$.fitted[which(datasubset$Year==2015)] - 2*augment(coho.adult.reg)$.se.fit[which(datasubset$Year==2015)]

polygon(c(rev(datasubset$Date[which(datasubset$Year==2015)]),datasubset$Date[which(datasubset$Year==2015)]),c(rev(y_up),y_down),col="grey80",border=NA)

points(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], lwd=2, type='b',pch=19,cex=0.25)

lines(datasubset$Date[which(datasubset$Year==2015)], augment(coho.adult.reg)$.fitted[which(datasubset$Year==2015)], lwd=2,lty=2, col="blue")

text(datasubset$Date[which(datasubset$Year==2015)][48],125,"2015",cex=1.5) 
```

```{r plot 2016 coho for gaussian}
plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], lwd=2, type='n',pch=19,cex=0.25,ylim=c(0,150),ylab="",xlab="",cex.lab=1.5)

y_up=augment(coho.adult.reg)$.fitted[which(datasubset$Year==2016)] + 2*augment(coho.adult.reg)$.se.fit[which(datasubset$Year==2016)]
 
y_down=augment(coho.adult.reg)$.fitted[which(datasubset$Year==2016)] - 2*augment(coho.adult.reg)$.se.fit[which(datasubset$Year==2016)]

polygon(c(rev(datasubset$Date[which(datasubset$Year==2016)]),datasubset$Date[which(datasubset$Year==2016)]),c(rev(y_up),y_down),col="grey80",border=NA)

points(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], lwd=2, type='b',pch=19,cex=0.25)

lines(datasubset$Date[which(datasubset$Year==2016)], augment(coho.adult.reg)$.fitted[which(datasubset$Year==2016)], lwd=2,lty=2, col="blue")
mtext("Coho Counts Gaussian model",side=2,cex=2,outer=T)
text(datasubset$Date[which(datasubset$Year==2016)][48],125,"2016",cex=1.5)
```

```{r total and predicted salmon}
#2015 total and predicted salmon
sum(predict(coho.adult.reg)[which(datasubset$Year==2015)])
sum(datasubset$Count[which(datasubset$Year==2015)])

#2016 total and predicted salmon
sum(predict(coho.adult.reg)[which(datasubset$Year==2016)])
sum(datasubset$Count[which(datasubset$Year==2016)])
```

```{r quasipoisson model}
# 2015 data
datasubset = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2015")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2015.reg <- glm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, family = "quasipoisson", data = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2015")) 
summary(coho.adult.2015.reg) 

# coho.adult.2015.reg <- glm(Count ~ QUANT_mean:Q_cfs2, family = "quasipoisson", data = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2015"))
# summary(coho.adult.2015.reg)


# 2016 data
datasubset = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2016")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2016.reg <- glm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, family = "quasipoisson", data = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2016"))
summary(coho.adult.2016.reg)

# coho.adult.2016.reg <- glm(Count ~ QUANT_mean:Q_cfs2, family = "quasipoisson", data = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2016"))
# summary(coho.adult.2016.reg)

tidy(coho.adult.2015.reg)
tidy(coho.adult.2016.reg)

# quasipoisson model with year interaction term
# year interaction is not sig, which is nice
datasubset = subset(coho_adult, Cohotype == "Coho_Adults" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))

coho.adult.reg <- glm(Count ~ QUANT_mean:Q_cfs2*Year+Temp_C, family = "quasipoisson", data = datasubset)
summary(coho.adult.reg)
tidy(coho.adult.reg)
# augment(coho.adult.reg)

# testing lagged terms
# coho.adult.reg <- glm(I(QUANT_mean*Q_cfs2)[3:39] ~ Count[1:37] +Count[2:38]+ Temp_C[3:39], family = "quasipoisson", data = datasubset[datasubset$Year==2016,])
# 
# coho.adult.reg <- glm(I(QUANT_mean*Q_cfs2)[2:39] ~ Count[1:38] + Temp_C[2:39], family = "quasipoisson", data = datasubset[datasubset$Year==2016,])
# summary(coho.adult.reg)
# augment(coho.adult.reg)

```

```{r fit 2016 quasipoisson model and apply to 2015}
# 2016 data and model
datasubset = subset(coho_adult, Cohotype == "Coho_Adults" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2016.reg <- glm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, family = "quasipoisson", data = datasubset[datasubset$Year == "2016", ])
summary(coho.adult.2016.reg)
tidy(coho.adult.2016.reg)
#                term   estimate std.error  statistic    p.value
# 1       (Intercept) -2.3250730 2.6859604 -0.8656394 0.39090662
# 2            Temp_C  0.1976748 0.1722527  1.1475866 0.25671154
# 3 QUANT_mean:Q_cfs2 19.4738980 8.7235963  2.2323245 0.03019675
coef(coho.adult.2016.reg)[1] # intercept
coef(coho.adult.2016.reg)[2] # Temp_C
coef(coho.adult.2016.reg)[3] # QUANT_mean:Q_cfs

# 2015 data and model
coho.adult.2015.reg <- glm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, family = "quasipoisson", data = datasubset[datasubset$Year == "2015", ])
summary(coho.adult.2015.reg)
tidy(coho.adult.2015.reg)
#                term   estimate  std.error statistic      p.value
# 1       (Intercept) 0.83942333 0.95454712 0.8793943 3.837585e-01
# 2            Temp_C 0.07838281 0.08728288 0.8980319 3.738451e-01
# 3 QUANT_mean:Q_cfs2 6.66879431 0.90099624 7.4015784 2.284307e-09
coef(coho.adult.2015.reg)[1] # intercept
coef(coho.adult.2015.reg)[2] # Temp_C
coef(coho.adult.2015.reg)[3] # QUANT_mean:Q_cfs


par(mfrow=c(2,1))
#plot2016
plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], type='l', ylim=c(0,200))
lines(datasubset$Date[which(datasubset$Year==2016)], exp(predict(coho.adult.2016.reg)), lty=2, col="black")
text(datasubset$Date[which(datasubset$Year==2016)][45],90,"2016",cex=1.5) 

#plot 2015 with 2016 model
plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], type='l', ylim=c(0,200))

lines(datasubset$Date[which(datasubset$Year==2015)], 
    exp(coef(coho.adult.2016.reg)[1] + 
    coef(coho.adult.2016.reg)[2] * datasubset$Temp_C[which(datasubset$Year==2015)] +
    coef(coho.adult.2016.reg)[3] * datasubset$QUANT_mean[which(datasubset$Year==2015)] * datasubset$Q_cfs2[which(datasubset$Year==2015)]), lty=2, col="black")
lines(datasubset$Date[which(datasubset$Year==2015)], 
    exp(coef(coho.adult.2015.reg)[1] + 
    coef(coho.adult.2015.reg)[2] * datasubset$Temp_C[which(datasubset$Year==2015)] +
    coef(coho.adult.2015.reg)[3] * datasubset$QUANT_mean[which(datasubset$Year==2015)] * datasubset$Q_cfs2[which(datasubset$Year==2015)]), lty=2, col="blue")
text(datasubset$Date[which(datasubset$Year==2015)][45],90,"2015",cex=1.5) 
par(mfrow=c(1,1))

#2015 total and predicted salmon
sum(exp(predict(coho.adult.2015.reg)))
sum(datasubset$Count[which(datasubset$Year==2015)])

#2016 total and predicted salmon
sum(exp(predict(coho.adult.2016.reg)))
sum(datasubset$Count[which(datasubset$Year==2016)])

```

```{r negative binomial model}
# library(MASS) # note that MASS::select collides with dplyr::select
# library(DHARMa)

# 2015 data
datasubset = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2015")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2015.reg <- glm.nb((Count+1) ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset) # count + 1 because there's a log link
summary(coho.adult.2015.reg) # Temp_C and QUANT*Qcfs both sig

# estimate residuals with DHARMa
simulationOutput <- simulateResiduals(fittedModel = coho.adult.2015.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T) # most predicted points are small and they are uniformly distributed
testUniformity(simulationOutput) # p = 0.440, D = 0.124, underoverdispersaion ns
testZeroInflation(simulationOutput)  # p = 0.943, ratioObsExp = 0

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C,  simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$QUANT_mean,  simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$Q_cfs2,  simulationOutput$scaledResiduals) # a bit heteroscedastic
plotResiduals(datasubset$QUANTQ,  simulationOutput$scaledResiduals) # basically uniform
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 6.392e-05, DW = 0.988, temp autocorr.  later residuals more likely to be positive
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.521 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# coho.adult.2015.reg <- glm.nb((Count+1) ~ QUANT_mean:Q_cfs2, data = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2015")) # count + 1 because there's a log link
# summary(coho.adult.2015.reg)
# simulationOutput <- simulateResiduals(fittedModel = coho.adult.2015.reg, n = 1000)
# plotSimulatedResiduals(simulationOutput = simulationOutput) # residuals worse than model without Temp_C

# 2016
datasubset = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2016")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2016.reg <- glm.nb((Count + 1) ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset) # count + 1 because there's a log link
summary(coho.adult.2016.reg)

# DHARMa residuals
simulationOutput <- simulateResiduals(fittedModel = coho.adult.2016.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput) # a bit heteroscedastic
testUniformity(simulationOutput) # p = 0.032, D = 0.200, underoverdispersaion ns
testZeroInflation(simulationOutput)  # p = 1, ratioObsExp = 0

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C, simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$QUANT_mean, simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$Q_cfs2, simulationOutput$scaledResiduals) # a bit heteroscedastic:  higher Q_cfs leads to more model underestimates
plotResiduals(datasubset$QUANTQ, simulationOutput$scaledResiduals) # basically uniform
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 4.863e-08, DW = 0.708, temp autocorr very sig:  more positive residuals later, so should I truncate the time series a bit?  and if so, where?
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.78 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# coho.adult.2016.reg <- glm.nb((Count + 1) ~ QUANT_mean:Q_cfs2, data = subset(coho_adult, Cohotype == "Coho_Adults" & Year == "2016")) # count + 1 because there's a log link
# summary(coho.adult.2016.reg)
# simulationOutput <- simulateResiduals(fittedModel = coho.adult.2016.reg, n = 1000)
# plotSimulatedResiduals(simulationOutput = simulationOutput)

tidy(coho.adult.2015.reg)
tidy(coho.adult.2016.reg)

# negative binomial model with year interaction term
# year interaction is not sig, which is nice
datasubset = subset(coho_adult, Cohotype == "Coho_Adults" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.reg <- glm.nb((Count + 1) ~ QUANT_mean:Q_cfs2*Year + Temp_C, data = datasubset) # count + 1 because there's a log link
summary(coho.adult.reg)
tidy(coho.adult.reg)
# augment(coho.adult.reg)

# DHARMa residuals
simulationOutput <- simulateResiduals(fittedModel = coho.adult.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput) # very few data at high predicted values, but at the low predicted values, residuals are nicely uniformly distributed. # we could say that residuals are a bit underdispersed. This leads to overwide CIs and p-values too small (so we should be more wary of concluding non-significance of a variable)
testUniformity(simulationOutput) # p = 0.009, D = 0.163, underoverdispersaion ns
testZeroInflation(simulationOutput)  # p = 1, ratioObsExp = 0

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C, simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$QUANT_mean, simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$Q_cfs2, simulationOutput$scaledResiduals) # a bit heteroscedastic
plotResiduals(datasubset$QUANTQ, simulationOutput$scaledResiduals) # basically uniform
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 1.237e-09, DW = 0.825, temp autocorr very sig:  more positive residuals later, so should I truncate the time series a bit?  and if so, where?
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.367, DW = 1.933 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# testing lagged terms
# coho.adult.reg <- glm(I(QUANT_mean*Q_cfs2)[3:39] ~ Count[1:37] +Count[2:38]+ Temp_C[3:39], family = "quasipoisson", data = datasubset[datasubset$Year==2016,])
# 
# coho.adult.reg <- glm(I(QUANT_mean*Q_cfs2)[2:39] ~ Count[1:38] + Temp_C[2:39], family = "quasipoisson", data = datasubset[datasubset$Year==2016,])
# summary(coho.adult.reg)
# augment(coho.adult.reg)
```

```{r fit 2016 negative binomial model and apply to 2015}
# 2016 data and model
datasubset = subset(coho_adult, Cohotype == "Coho_Adults" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2016.reg <- glm.nb((Count+1) ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset[datasubset$Year == "2016", ])
summary(coho.adult.2016.reg)
tidy(coho.adult.2016.reg)
#                term   estimate  std.error statistic     p.value
# 1       (Intercept) -1.4427996 1.01160855 -1.426243 0.153798231
# 2            Temp_C  0.1735155 0.06724403  2.580385 0.009869023
# 3 QUANT_mean:Q_cfs2 13.9214472 4.95262797  2.810921 0.004939987
coef(coho.adult.2016.reg)[1] # intercept
coef(coho.adult.2016.reg)[2] # Temp_C
coef(coho.adult.2016.reg)[3] # QUANT_mean:Q_cfs

# 2015 data and model
coho.adult.2015.reg <- glm.nb((Count+1) ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset[datasubset$Year == "2015", ])
summary(coho.adult.2015.reg)
tidy(coho.adult.2015.reg)
#                term   estimate  std.error statistic      p.value
# 1       (Intercept) 0.57812589 0.77317166 0.7477329 4.546213e-01
# 2            Temp_C 0.09154096 0.06930009 1.3209356 1.865229e-01
# 3 QUANT_mean:Q_cfs2 9.05192303 1.44430644 6.2673147 3.673273e-10
coef(coho.adult.2015.reg)[1] # intercept
coef(coho.adult.2015.reg)[2] # Temp_C
coef(coho.adult.2015.reg)[3] # QUANT_mean:Q_cfs


par(mfrow=c(2,1))
#plot2016
plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], type='l', ylim=c(0,200))
lines(datasubset$Date[which(datasubset$Year==2016)], exp(predict(coho.adult.2016.reg)), lty=2, col="black")
text(datasubset$Date[which(datasubset$Year==2016)][45],150,"2016",cex=1.5) 

#plot 2015 with 2016 model
plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], type='l', ylim=c(0,200))

lines(datasubset$Date[which(datasubset$Year==2015)], 
    exp(coef(coho.adult.2016.reg)[1] + 
    coef(coho.adult.2016.reg)[2] * datasubset$Temp_C[which(datasubset$Year==2015)] +
    coef(coho.adult.2016.reg)[3] * datasubset$QUANT_mean[which(datasubset$Year==2015)] * datasubset$Q_cfs2[which(datasubset$Year==2015)]), lty=2, col="black")
lines(datasubset$Date[which(datasubset$Year==2015)], 
    exp(coef(coho.adult.2015.reg)[1] + 
    coef(coho.adult.2015.reg)[2] * datasubset$Temp_C[which(datasubset$Year==2015)] +
    coef(coho.adult.2015.reg)[3] * datasubset$QUANT_mean[which(datasubset$Year==2015)] * datasubset$Q_cfs2[which(datasubset$Year==2015)]), lty=2, col="blue")
text(datasubset$Date[which(datasubset$Year==2015)][45],150,"2015",cex=1.5) 
par(mfrow=c(1,1))

#2015 total and predicted salmon
sum(exp(predict(coho.adult.2015.reg)))
sum(datasubset$Count[which(datasubset$Year==2015)])

#2016 total and predicted salmon
sum(exp(predict(coho.adult.2016.reg)))
sum(datasubset$Count[which(datasubset$Year==2016)])

```

```{r plot 2015 coho for negbin and poisson}
par(mfrow=c(2,1),mar=c(2,3,1,1),oma=c(1,3,1,1))

plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], lwd=2, type='n',pch=19,cex=0.25,ylim=c(0,200),ylab="",xlab="",cex.lab=1.5)

y_up=exp(augment(coho.adult.reg)$.fitted + 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2015)]
 
y_down=exp(augment(coho.adult.reg)$.fitted - 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2015)]

polygon(c(rev(datasubset$Date[which(datasubset$Year==2015)]),datasubset$Date[which(datasubset$Year==2015)]),c(rev(y_up),y_down),col="grey80",border=NA)

points(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], lwd=2, type='b',pch=19,cex=0.25)

lines(datasubset$Date[which(datasubset$Year==2015)], exp(augment(coho.adult.reg)$.fitted)[which(datasubset$Year==2015)], lwd=2,lty=2, col="blue")
text(datasubset$Date[which(datasubset$Year==2015)][48],150,"2015",cex=1.5) 
 
```

```{r plot 2016 coho for negbin and poisson}
plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], lwd=2, type='n',pch=19,cex=0.25,ylim=c(0,200),ylab="",xlab="",cex.lab=1.5)

y_up=exp(augment(coho.adult.reg)$.fitted + 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2016)]
 
y_down=exp(augment(coho.adult.reg)$.fitted - 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2016)]

polygon(c(rev(datasubset$Date[which(datasubset$Year==2016)]),datasubset$Date[which(datasubset$Year==2016)]),c(rev(y_up),y_down),col="grey80",border=NA)

points(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], lwd=2, type='b',pch=19,cex=0.25)

lines(datasubset$Date[which(datasubset$Year==2016)], exp(augment(coho.adult.reg)$.fitted)[which(datasubset$Year==2016)], lwd=2,lty=2, col="blue")
mtext("Coho Counts Quasipoisson model",side=2,cex=2,outer=T)
text(datasubset$Date[which(datasubset$Year==2016)][48],150,"2016",cex=1.5)
# 
# lines(datasubset$Date[which(datasubset$Year==2016)], exp(augment(coho.adult.reg)$.fitted + 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2016)], lwd=2,lty=3, col="darkgray")
# 
# lines(datasubset$Date[which(datasubset$Year==2016)], exp(augment(coho.adult.reg)$.fitted - 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2016)], lwd=2,lty=3, col="darkgray")

# plot 2015
# plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], type='b',pch=19,cex=0.25,ylim=c(0,800),lwd=2,ylab="Coho Counts",xlab="")
# 
# #add confint augment(coho.adult.reg)
# lines(datasubset$Date[which(datasubset$Year==2015)], exp(augment(coho.adult.reg)$.fitted)[which(datasubset$Year==2015)], lwd=2,lty=2, col="blue")
# 
# lines(datasubset$Date[which(datasubset$Year==2015)], exp(augment(coho.adult.reg)$.fitted + 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2015)], lwd=2,lty=3, col="darkgray")
# 
# lines(datasubset$Date[which(datasubset$Year==2015)], exp(augment(coho.adult.reg)$.fitted - 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2015)], lwd=2,lty=3, col="darkgray")


#2015 total and predicted salmon
sum(exp(predict(coho.adult.reg))[which(datasubset$Year==2015)])
sum(datasubset$Count[which(datasubset$Year==2015)])

#2016 total and predicted salmon
sum(exp(predict(coho.adult.reg))[which(datasubset$Year==2016)])
sum(datasubset$Count[which(datasubset$Year==2016)])
```


Coho_total models
```{r linear model}
# 2015 data
datasubset = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2015")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2015.reg <- lm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset) 
summary(coho.adult.2015.reg)

# estimate residuals with DHARMa
plotConventionalResiduals(coho.adult.2015.reg)
simulationOutput <- simulateResiduals(fittedModel = coho.adult.2015.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T) # are uniform except for lowest predicted values
testUniformity(simulationOutput) # p = 0.063, D = 0.182, overdispersaion ns

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C,  simulationOutput$scaledResiduals) # uniform
plotResiduals(datasubset$QUANT_mean,  simulationOutput$scaledResiduals) # a bit heteroscedastic
plotResiduals(datasubset$Q_cfs2,  simulationOutput$scaledResiduals) # a bit heteroscedastic
plotResiduals(datasubset$QUANTQ,  simulationOutput$scaledResiduals) # basically uniform to a bit overdispersed
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 0.001, DW = 1.18, temp autocorr sig, later residuals more likely to be positive
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.424 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# coho.adult.2015.reg <- lm(Count ~ QUANT_mean:Q_cfs2, data = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2015"))
# summary(coho.adult.2015.reg)

# 2016 data
datasubset = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2016")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2016.reg <- lm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, data = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2016"))
summary(coho.adult.2016.reg)

# estimate residuals with DHARMa
plotConventionalResiduals(coho.adult.2016.reg)
simulationOutput <- simulateResiduals(fittedModel = coho.adult.2016.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T) # overdispersed and non-normal residuals
testUniformity(simulationOutput) # p = 0.06, D = 0.279, overdispersaion highly sig

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C,  simulationOutput$scaledResiduals) # heteroscedastic
plotResiduals(datasubset$QUANT_mean,  simulationOutput$scaledResiduals) # heteroscedastic
plotResiduals(datasubset$Q_cfs2,  simulationOutput$scaledResiduals) # heteroscedastic
plotResiduals(datasubset$QUANTQ,  simulationOutput$scaledResiduals) # heteroscedastic
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 2.46e-06, DW = 0.855, temp autocorr highly sig, later residuals are positive
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.958 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

tidy(coho.adult.2015.reg)
tidy(coho.adult.2016.reg)

# coho.adult.2016.reg <- lm(Count ~ QUANT_mean:Q_cfs2, data = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2016"))
# summary(coho.adult.2016.reg)

# 2015 & 2016 data:   with Year interaction term.  year interaction is not sig, which is nice
datasubset = subset(coho_adult, Cohotype == "Coho_Total" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.reg <- lm((Count) ~ QUANT_mean:Q_cfs2*Year+Temp_C, data = datasubset)
summary(coho.adult.reg)

simulationOutput <- simulateResiduals(fittedModel = coho.adult.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T) # a bit overdispersed
testUniformity(simulationOutput) # p = 0.011, D = 0.160, overdispersaion highly sig

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C,  simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$QUANT_mean,  simulationOutput$scaledResiduals) # a bit of overdispersion
plotResiduals(datasubset$Q_cfs2,  simulationOutput$scaledResiduals) # a bit of overdispersion
plotResiduals(datasubset$QUANTQ,  simulationOutput$scaledResiduals) # a bit of overdispersion
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 7.825e-07, DW = 1.05, temp autocorr, 2016 is driving this 
testTemporalAutocorrelation(simulationOutput = simulationOutput, plot = T) # p = 0.360 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# conventional residuals for linear models
plotConventionalResiduals(coho.adult.reg)

par(mfrow=c(2,2))
plot(coho.adult.reg)
par(mfrow=c(1,1))
glance(coho.adult.reg)

# augment(coho.adult.reg)
# 
# #plot2016
# par(mfrow=c(2,1))
# plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], type='l')
# 
# lines(datasubset$Date[which(datasubset$Year==2016)], (predict(coho.adult.reg))[which(datasubset$Year==2016)], lty=2, col="blue")
# 
# #plot 2015
# plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], type='l')
# 
# lines(datasubset$Date[which(datasubset$Year==2015)], (predict(coho.adult.reg))[which(datasubset$Year==2015)], lty=2, col="blue")
# par(mfrow=c(1,1))
# 
# #2015 total and predicted salmon
# sum((predict(coho.adult.reg))[which(datasubset$Year==2015)])
# sum(datasubset$Count[which(datasubset$Year==2015)])
# 
# #2016 total and predicted salmon
# sum((predict(coho.adult.reg))[which(datasubset$Year==2016)])
# sum(datasubset$Count[which(datasubset$Year==2016)])
```

```{r plot 2015 coho for gaussian}
par(mfrow=c(2,1),mar=c(2,3,1,1),oma=c(1,3,1,1))

plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], lwd=2, type='n',pch=19,cex=0.25,ylim=c(0,150),ylab="",xlab="",cex.lab=1.5)

y_up=augment(coho.adult.reg)$.fitted[which(datasubset$Year==2015)] + 2*augment(coho.adult.reg)$.se.fit[which(datasubset$Year==2015)]
 
y_down=augment(coho.adult.reg)$.fitted[which(datasubset$Year==2015)] - 2*augment(coho.adult.reg)$.se.fit[which(datasubset$Year==2015)]

polygon(c(rev(datasubset$Date[which(datasubset$Year==2015)]),datasubset$Date[which(datasubset$Year==2015)]),c(rev(y_up),y_down),col="grey80",border=NA)

points(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], lwd=2, type='b',pch=19,cex=0.25)

lines(datasubset$Date[which(datasubset$Year==2015)], augment(coho.adult.reg)$.fitted[which(datasubset$Year==2015)], lwd=2,lty=2, col="blue")

text(datasubset$Date[which(datasubset$Year==2015)][48],125,"2015",cex=1.5) 
```

```{r plot 2016 coho for gaussian}
plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], lwd=2, type='n',pch=19,cex=0.25,ylim=c(0,150),ylab="",xlab="",cex.lab=1.5)

y_up=augment(coho.adult.reg)$.fitted[which(datasubset$Year==2016)] + 2*augment(coho.adult.reg)$.se.fit[which(datasubset$Year==2016)]
 
y_down=augment(coho.adult.reg)$.fitted[which(datasubset$Year==2016)] - 2*augment(coho.adult.reg)$.se.fit[which(datasubset$Year==2016)]

polygon(c(rev(datasubset$Date[which(datasubset$Year==2016)]),datasubset$Date[which(datasubset$Year==2016)]),c(rev(y_up),y_down),col="grey80",border=NA)

points(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], lwd=2, type='b',pch=19,cex=0.25)

lines(datasubset$Date[which(datasubset$Year==2016)], augment(coho.adult.reg)$.fitted[which(datasubset$Year==2016)], lwd=2,lty=2, col="blue")
mtext("Coho Total Counts Gaussian model",side=2,cex=2,outer=T)
text(datasubset$Date[which(datasubset$Year==2016)][48],125,"2016",cex=1.5)
```

```{r total and predicted salmon}
#2015 total and predicted salmon
sum(predict(coho.adult.reg)[which(datasubset$Year==2015)])
sum(datasubset$Count[which(datasubset$Year==2015)])

#2016 total and predicted salmon
sum(predict(coho.adult.reg)[which(datasubset$Year==2016)])
sum(datasubset$Count[which(datasubset$Year==2016)])
```

```{r quasipoisson model}
# 2015 data
datasubset = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2015")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2015.reg <- glm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, family = "quasipoisson", data = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2015")) 
summary(coho.adult.2015.reg) 

# coho.adult.2015.reg <- glm(Count ~ QUANT_mean:Q_cfs2, family = "quasipoisson", data = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2015"))
# summary(coho.adult.2015.reg)


# 2016 data
datasubset = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2016")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2016.reg <- glm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, family = "quasipoisson", data = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2016"))
summary(coho.adult.2016.reg)

# coho.adult.2016.reg <- glm(Count ~ QUANT_mean:Q_cfs2, family = "quasipoisson", data = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2016"))
# summary(coho.adult.2016.reg)

tidy(coho.adult.2015.reg)
tidy(coho.adult.2016.reg)

# quasipoisson model with year interaction term
# year interaction is not sig, which is nice
datasubset = subset(coho_adult, Cohotype == "Coho_Total" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))

coho.adult.reg <- glm(Count ~ QUANT_mean:Q_cfs2*Year+Temp_C, family = "quasipoisson", data = datasubset)
summary(coho.adult.reg)
tidy(coho.adult.reg)
# augment(coho.adult.reg)

# testing lagged terms
# coho.adult.reg <- glm(I(QUANT_mean*Q_cfs2)[3:39] ~ Count[1:37] +Count[2:38]+ Temp_C[3:39], family = "quasipoisson", data = datasubset[datasubset$Year==2016,])
# 
# coho.adult.reg <- glm(I(QUANT_mean*Q_cfs2)[2:39] ~ Count[1:38] + Temp_C[2:39], family = "quasipoisson", data = datasubset[datasubset$Year==2016,])
# summary(coho.adult.reg)
# augment(coho.adult.reg)

```

There is a strong negative-quadratic effect of Temp_C, which i think is just coincidental, so i don't include it
```{r negative binomial model}
# library(MASS) # note that MASS::select collides with dplyr::select
# library(DHARMa)
 
# 2015 data 
datasubset = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2015")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs2) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2015.reg <- glm.nb((Count+1) ~ QUANT_mean:Q_cfs2 + Temp_C, data = datasubset) # count + 1 because there's a log link
summary(coho.adult.2015.reg) # Temp_C and QUANT*Qcfs both sig

# estimate residuals with DHARMa
simulationOutput <- simulateResiduals(fittedModel = coho.adult.2015.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T) # most predicted points are small and they are uniformly distributed
testUniformity(simulationOutput) # p = 0.933, D = 0.077, underoverdispersaion ns
testZeroInflation(simulationOutput)  # p = 0.663, ratioObsExp = 0

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C,  simulationOutput$scaledResiduals) # a bit heteroscedastic
plotResiduals(datasubset$QUANT_mean,  simulationOutput$scaledResiduals) # a bit heteroscedastic
plotResiduals(datasubset$Q_cfs2,  simulationOutput$scaledResiduals) # a bit heteroscedastic
plotResiduals(datasubset$QUANTQ,  simulationOutput$scaledResiduals) # a bit heteroscedastic
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 1.577e-05, DW = 0.914, temp autocorr.  later residuals more likely to be positive
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.561 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# coho.adult.2015.reg <- glm.nb((Count+1) ~ QUANT_mean:Q_cfs2, data = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2015")) # count + 1 because there's a log link
# summary(coho.adult.2015.reg)
# simulationOutput <- simulateResiduals(fittedModel = coho.adult.2015.reg, n = 1000)
# plotSimulatedResiduals(simulationOutput = simulationOutput) # residuals worse than model without Temp_C

# 2016
datasubset = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2016")
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.2016.reg <- glm.nb((Count + 1) ~ QUANT_mean:Q_cfs2 + Temp_C + I(Temp_C^2), data = datasubset) # count + 1 because there's a log link
summary(coho.adult.2016.reg)

# DHARMa residuals
simulationOutput <- simulateResiduals(fittedModel = coho.adult.2016.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput) # a bit heteroscedastic
testUniformity(simulationOutput) # p = 0.487, D = 0.116, underoverdispersaion ns
testZeroInflation(simulationOutput)  # p = 0.64, ratioObsExp = 0

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C, simulationOutput$scaledResiduals) # negative quadratic!
plotResiduals(datasubset$QUANT_mean, simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$Q_cfs2, simulationOutput$scaledResiduals) # a bit heteroscedastic:  higher Q_cfs leads to more model underestimates
plotResiduals(datasubset$QUANTQ, simulationOutput$scaledResiduals) # underdispersed
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 4.863e-08, DW = 0.708, temp autocorr very sig:  more positive residuals later, so should I truncate the time series a bit?  and if so, where?
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.78 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# coho.adult.2016.reg <- glm.nb((Count + 1) ~ QUANT_mean:Q_cfs2, data = subset(coho_adult, Cohotype == "Coho_Total" & Year == "2016")) # count + 1 because there's a log link
# summary(coho.adult.2016.reg)
# simulationOutput <- simulateResiduals(fittedModel = coho.adult.2016.reg, n = 1000)
# plotSimulatedResiduals(simulationOutput = simulationOutput)

tidy(coho.adult.2015.reg)
tidy(coho.adult.2016.reg)

# negative binomial model with year interaction term
# year interaction is not sig, which is nice
datasubset = subset(coho_adult, Cohotype == "Coho_Total" &!is.na(QUANT_mean) & Year %in% c("2015", "2016"))
datasubset <- datasubset %>% dplyr::filter(!is.na(QUANT_mean))
datasubset <- datasubset %>% mutate(QUANTQ = QUANT_mean * Q_cfs) # to allow plotting of residuals against QUANT_mean * Q_cfs

coho.adult.reg <- glm.nb((Count + 1) ~ QUANT_mean:Q_cfs2*Year + Temp_C, data = datasubset) # count + 1 because there's a log link
summary(coho.adult.reg)
tidy(coho.adult.reg)
# augment(coho.adult.reg)

# DHARMa residuals
simulationOutput <- simulateResiduals(fittedModel = coho.adult.reg, n = 1000)
plotSimulatedResiduals(simulationOutput = simulationOutput) # very few data at high predicted values, but at the low predicted values, residuals are nicely uniformly distributed. # we could say that residuals are a bit underdispersed. This leads to overwide CIs and p-values too small (so we should be more wary of concluding non-significance of a variable)
testUniformity(simulationOutput) # p = 0.009, D = 0.163, underoverdispersaion ns
testZeroInflation(simulationOutput)  # p = 1, ratioObsExp = 0

# plot residuals against predictors
par(mfrow = c(2,2))
plotResiduals(datasubset$Temp_C, simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$QUANT_mean, simulationOutput$scaledResiduals) # basically uniform
plotResiduals(datasubset$Q_cfs2, simulationOutput$scaledResiduals) # a bit heteroscedastic
plotResiduals(datasubset$QUANTQ, simulationOutput$scaledResiduals) # basically uniform
par(mfrow = c(1,1))

testTemporalAutocorrelation(simulationOutput = simulationOutput, time = datasubset$Date, plot = T) # p = 1.237e-09, DW = 0.825, temp autocorr very sig:  more positive residuals later, so should I truncate the time series a bit?  and if so, where?
testTemporalAutocorrelation(simulationOutput = simulationOutput,  plot = T) # p = 0.367, DW = 1.933 for a random order of datapoints (null expectation of p for truly non-temp-corr data)

# testing lagged terms
# coho.adult.reg <- glm(I(QUANT_mean*Q_cfs2)[3:39] ~ Count[1:37] +Count[2:38]+ Temp_C[3:39], family = "quasipoisson", data = datasubset[datasubset$Year==2016,])
# 
# coho.adult.reg <- glm(I(QUANT_mean*Q_cfs2)[2:39] ~ Count[1:38] + Temp_C[2:39], family = "quasipoisson", data = datasubset[datasubset$Year==2016,])
# summary(coho.adult.reg)
# augment(coho.adult.reg)
```

```{r plot 2015 coho for negbin and poisson}
par(mfrow=c(2,1),mar=c(2,3,1,1),oma=c(1,3,1,1))

plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], lwd=2, type='n',pch=19,cex=0.25,ylim=c(0,200),ylab="",xlab="",cex.lab=1.5)

y_up=exp(augment(coho.adult.reg)$.fitted + 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2015)]
 
y_down=exp(augment(coho.adult.reg)$.fitted - 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2015)]

polygon(c(rev(datasubset$Date[which(datasubset$Year==2015)]),datasubset$Date[which(datasubset$Year==2015)]),c(rev(y_up),y_down),col="grey80",border=NA)

points(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], lwd=2, type='b',pch=19,cex=0.25)

lines(datasubset$Date[which(datasubset$Year==2015)], exp(augment(coho.adult.reg)$.fitted)[which(datasubset$Year==2015)], lwd=2,lty=2, col="blue")
text(datasubset$Date[which(datasubset$Year==2015)][48],150,"2015",cex=1.5) 
```

```{r plot 2016 coho for negbin and poisson}
plot(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], lwd=2, type='n',pch=19,cex=0.25,ylim=c(0,200),ylab="",xlab="",cex.lab=1.5)

y_up=exp(augment(coho.adult.reg)$.fitted + 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2016)]
 
y_down=exp(augment(coho.adult.reg)$.fitted - 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2016)]

polygon(c(rev(datasubset$Date[which(datasubset$Year==2016)]),datasubset$Date[which(datasubset$Year==2016)]),c(rev(y_up),y_down),col="grey80",border=NA)

points(datasubset$Date[which(datasubset$Year==2016)], datasubset$Count[which(datasubset$Year==2016)], lwd=2, type='b',pch=19,cex=0.25)

lines(datasubset$Date[which(datasubset$Year==2016)], exp(augment(coho.adult.reg)$.fitted)[which(datasubset$Year==2016)], lwd=2,lty=2, col="blue")
mtext("Coho Total Negative Binomial model",side=2,cex=2,outer=T)
text(datasubset$Date[which(datasubset$Year==2016)][48],150,"2016",cex=1.5)
# 
# lines(datasubset$Date[which(datasubset$Year==2016)], exp(augment(coho.adult.reg)$.fitted + 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2016)], lwd=2,lty=3, col="darkgray")
# 
# lines(datasubset$Date[which(datasubset$Year==2016)], exp(augment(coho.adult.reg)$.fitted - 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2016)], lwd=2,lty=3, col="darkgray")

# plot 2015
# plot(datasubset$Date[which(datasubset$Year==2015)], datasubset$Count[which(datasubset$Year==2015)], type='b',pch=19,cex=0.25,ylim=c(0,800),lwd=2,ylab="Coho Counts",xlab="")
# 
# #add confint augment(coho.adult.reg)
# lines(datasubset$Date[which(datasubset$Year==2015)], exp(augment(coho.adult.reg)$.fitted)[which(datasubset$Year==2015)], lwd=2,lty=2, col="blue")
# 
# lines(datasubset$Date[which(datasubset$Year==2015)], exp(augment(coho.adult.reg)$.fitted + 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2015)], lwd=2,lty=3, col="darkgray")
# 
# lines(datasubset$Date[which(datasubset$Year==2015)], exp(augment(coho.adult.reg)$.fitted - 2*augment(coho.adult.reg)$.se.fit)[which(datasubset$Year==2015)], lwd=2,lty=3, col="darkgray")
```

```{r total and predicted coho}
#2015 total and predicted salmon
sum(exp(predict(coho.adult.reg))[which(datasubset$Year==2015)])
sum(datasubset$Count[which(datasubset$Year==2015)])

#2016 total and predicted salmon
sum(exp(predict(coho.adult.reg))[which(datasubset$Year==2016)])
sum(datasubset$Count[which(datasubset$Year==2016)])
```




Archived code below this

```{r DHARMa tutorial from package vignette}
library(DHARMa)
simulationOutput <- simulateResiduals(fittedModel = fittedModel, n = 250)
plotSimulatedResiduals(simulationOutput = simulationOutput)
plotResiduals(YOURPREDICTOR, simulationOutput$scaledResiduals)
testUniformity(simulationOutput = simulationOutput)
testOverdispersion(simulationOutput = simulationOutput) # use refit = T in simulateResiduals()
testZeroinflation(simulationOutput = simulationOutput)
testTemporalAutocorrelation(simulationOutput = simulationOutput)
testSpatialAutocorrelation(simulationOutput = simulationOutput)
?simulateResiduals

# overdispersion example
library(lme4)
testData = createData(sampleSize = 500, overdispersion = 2, family = poisson())
fittedModel <- glmer(observedResponse ~ Environment1 + (1|group) , family = "poisson", data = testData)

simulationOutput <- simulateResiduals(fittedModel = fittedModel)
plotSimulatedResiduals(simulationOutput = simulationOutput) # too many residuals around 0 and 1
testUniformity(simulationOutput = simulationOutput) # standard test

# a more powerful test but slow
simulationOutput2 <- simulateResiduals(fittedModel = fittedModel, refit = T, n = 250)
testOverdispersion(simulationOutput2)

# a faster test but slightly less powerful than above 
testOverdispersionParametric(simulationOutput) # more powerful than testUniformity but can't run with Poisson GLMs so not useful here.

# underdispersion example
testData = createData(sampleSize = 500, intercept=0, fixedEffects = 2, overdispersion = 0, family = poisson(), roundPoissonVariance = 0.001, randomEffectVariance = 0)
fittedModel <- glmer(observedResponse ~ Environment1 + (1|group) , family = "poisson", data = testData)

summary(fittedModel)
simulationOutput <- simulateResiduals(fittedModel = fittedModel)
plotSimulatedResiduals(simulationOutput = simulationOutput) # too many residuals around 0.5
testUniformity(simulationOutput = simulationOutput)

# zero-inflation example
testData = createData(sampleSize = 500, intercept = 2, fixedEffects = c(1), overdispersion = 0, family = poisson(), quadraticFixedEffects = c(-3), randomEffectVariance = 0, pZeroInflation = 0.6)

par(mfrow = c(1,2))
plot(testData$Environment1, testData$observedResponse, xlab = "Envrionmental Predictor", ylab = "Response")
hist(testData$observedResponse, xlab = "Response", main = "")
par(mfrow = c(1,1))
fittedModel <- glmer(observedResponse ~ Environment1 + I(Environment1^2) + (1|group) , family = "poisson", data = testData)

simulationOutput <- simulateResiduals(fittedModel = fittedModel)
plotSimulatedResiduals(simulationOutput = simulationOutput) # looks like overdispersion because the model will usually try to find a compromise between the zeros, and the other values, which will lead to excess variance in the residuals.  Note that overdispersion will also lead to excess zeros, so only seeing too many zeros is not a reliable diagnostics for moving towards a zero-inflated model. A reliable differentiation between overdispersion and zero-inflation will usually only be possible when directly comparing alternative models, e.g. through residual comparison / model selection of a model with / without zero-inflation, or by simply fitting a model with zero-inflation and looking at the parameter estimate for the zero-inflation.
testZeroInflation(simulationOutput)

# heteroscedasticity example.  difficult to detect with standard residuals plots.  Heteroscedasticity means that there is a systematic dependency of the dispersion / variance on another variable in the model. It is not sufficiently appreciated that also binomial or Poisson models can show heteroscedasticity. Basically, it means that the level of over/underdispersion depends on another parameter. Here an example where we create such data
testData = createData(sampleSize = 500, intercept = 0, overdispersion = function(x){return(rnorm(length(x), sd = 2*abs(x)))}, family = poisson(), randomEffectVariance = 0)
fittedModel <- glmer(observedResponse ~ Environment1 + (1|group), family = "poisson", data = testData)

simulationOutput <- simulateResiduals(fittedModel = fittedModel)
plotSimulatedResiduals(simulationOutput = simulationOutput)
testUniformity(simulationOutput = simulationOutput)

# fit a model with an overdispersion parameter
testData = createData(sampleSize = 500, intercept = 0, overdispersion = function(x){return(rnorm(length(x), sd = 2*abs(x)))}, family = poisson(), randomEffectVariance = 0)
fittedModel <- glmer(observedResponse ~ Environment1 + (1|group) + (1|ID), family = "poisson", data = testData)

plotConventionalResiduals(fittedModel)

simulationOutput <- simulateResiduals(fittedModel = fittedModel)
plotSimulatedResiduals(simulationOutput = simulationOutput)
testUniformity(simulationOutput = simulationOutput)

# Missing predictors or quadratic effects.  A second test that is typically run for LMs, but not for GL(M)Ms is to plot residuals against the predictors in the model (or potentially predictors that were not in the model) to detect possible misspecifications. Doing this is highly recommended. For that purpose, you can retrieve the residuals via
simulationOutput$scaledResiduals
# Note again that the residual values are scaled between 0 and 1. If you plot the residuals against predictors, space or time, the resulting plots should not only show no systematic dependency of those residuals on the covariates, but they should also again be flat for each fixed situation. That means that if you have, for example, a categorical predictor: treatment / control, the distribution of residuals for each predictor alone should be flat as well.

testData = createData(sampleSize = 200, intercept = 1, fixedEffects = c(1,2), overdispersion = 0, family = poisson(), quadraticFixedEffects = c(-3,0))
fittedModel <- glmer(observedResponse ~ Environment1 + Environment2 + (1|group) , family = "poisson", data = testData)
simulationOutput <- simulateResiduals(fittedModel = fittedModel)
# plotConventionalResiduals(fittedModel)
plotSimulatedResiduals(simulationOutput = simulationOutput, quantreg = T)
testUniformity(simulationOutput = simulationOutput)
# It is difficult to see that there is a problem at all in the general plot, but it becomes clear if we plot against the environment
par(mfrow = c(1,2))
plotResiduals(testData$Environment1,  simulationOutput$scaledResiduals)
plotResiduals(testData$Environment2,  simulationOutput$scaledResiduals)
par(mfrow = c(1,1))
# temporal autocorrelation
# A special case of plotting residuals against predictors is the plot against time and space, which should always be performed if those variables are present in the model. Lets create some temporally autocorrelated data
testData = createData(sampleSize = 100, family = poisson(), temporalAutocorrelation = 5)

fittedModel <- glmer(observedResponse ~ Environment1 + (1|group), data = testData, family = poisson() )

simulationOutput <- simulateResiduals(fittedModel = fittedModel)
testTemporalAutocorrelation(simulationOutput = simulationOutput, time = testData$time)
```

```{r}
sockeye.adult.2016.reg <- glm(Count ~ QUANT_mean:Q_cfs2 + Temp_C, family = "quasipoisson", data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year %in% c("2015", "2016")))
summary(sockeye.adult.2016.reg)

sockeye.adult.2016.reg <- glm(Count ~ QUANT_mean:Q_cfs2, family = "quasipoisson", data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year %in% c("2015", "2016")))
summary(sockeye.adult.2016.reg) 
 
```

```{r confidence interval code snippet, eval = FALSE, include = FALSE}
x= 1:20

y=6*exp(.2*x + rnorm(20,0,0.5))
mod=lm(log(y)~x)
plot(x,y)

newx=seq(min(x),max(x),length.out=100)
preds=predict(mod,newdata=data.frame(x=newx),interval="confidence")
plot(log(y)~x, type='n')
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]),col="grey80",border=NA)
points(x,log(y))

plot((y)~x, type='n')
polygon(c(rev(newx),newx), exp(c(rev(preds[,3]),preds[,2])),col="grey80",border=NA)
points(x,y)
lines(newx,exp(preds[,1]))

```

```{r archived code, eval=FALSE, include=FALSE}
# # calc consistent QUANT_mean from CT_mean}
# plot(log(QUANT_mean) ~ CT_mean, col = as.numeric(Year), data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == c("2015")))
# qpcrmod <- lm(log(QUANT_mean) ~ CT_mean, data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2016"))
# summary(qpcrmod)
# tidy(qpcrmod)
# #          term   estimate  std.error statistic      p.value
# # 1 (Intercept) 16.9888183 0.92435853  18.37904 3.411463e-20
# # 2     CT_mean -0.7129658 0.02604225 -27.37728 3.681025e-26
# # QUANT_mean = exp(16.9888183 - 0.7129658 * CT_mean)
# 
# sockeye_adult <- sockeye_adult %>% mutate(QUANT_mean2 = exp(16.9888183 - 0.7129658 * CT_mean))
# coho_adult <- coho_adult %>% mutate(QUANT_mean2 = exp(16.9888183 - 0.7129658 * CT_mean))
# plot(log(QUANT_mean2) ~ CT_mean, col = as.numeric(Year), data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == c("2016", "2015")))
# 
# plot(QUANT_mean2 ~ QUANT_mean, col = as.numeric(Year), data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == c("2016", "2015")))
# 
# plot(QUANT_mean2 ~ QUANT_mean, col = as.numeric(Year), data = subset(coho_adult, Cohotype == "Coho_Adults" & Year == c("2016", "2015")))
# 
# plot(QUANT_mean ~ CT_mean, col = as.numeric(Year), data = subset(coho_adult, Cohotype == "Coho_Adults" & Year == c("2016", "2015")))
# 
# hist(sockeye_adult$QUANT_mean, data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == c("2016", "2015")))
# hist(sockeye_adult$QUANT_mean2, data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == c("2016", "2015")))
```

```{r archived code2, eval=FALSE, include=FALSE}



sockeye.adult.2015.reg <- glm(Count ~  Qcorr_qPCR,family = "quasipoisson", data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2015"))

plot(CT_mean*log(Gage_Height) ~  Qcorr_qPCR, data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2015"))
plot(CT_mean~QUANT_mean , data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2015"))

plot((CT_mean)~log(QUANT_mean) , data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2016"),pch=2)
exp(CT_mean)*log(gage)
log(flow)=a + b*log(gage)
flow=e^a * gage^b

plot(CT_mean~QUANT_mean , data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2014"),pch=2)

sockeye.adult.2016.reg <- lm(log(Count+1) ~ CT_mean*log(Gage_Height) , data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults" & Year == "2016"))

sockeye.adult.reg <- lm(log(Count+1)~ CT_mean*log(Gage_Height) , data = subset(sockeye_adult, Sockeyetype == "Sockeye_Adults"))

summary(sockeye.adult.2014.reg); AIC(sockeye.adult.2014.reg)
summary(sockeye.adult.2015.reg); AIC(sockeye.adult.2015.reg)
summary(sockeye.adult.2016.reg); AIC(sockeye.adult.2016.reg)
summary(sockeye.adult.reg)




sockeye.adult.2016.reg=lm(log(Count+1)~ CT_mean*log(Q_cfs),data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"&Year=="2016"))

summary(sockeye.adult.2016.reg)
AIC(sockeye.adult.2016.reg)
plot( log(subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"&Year=="2016"&!is.na(CT_mean))$Count+1),predict(sockeye.adult.2016.reg));abline(0,1)

sockeye.adult.2016.pois.reg=glm(Count~ CT_mean*log(Q_cfs),family="quasipoisson",data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"&Year=="2016"))
summary(sockeye.adult.2016.pois.reg)
plot( log(subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"&Year=="2016"&!is.na(CT_mean))$Count+1),(predict(sockeye.adult.2016.pois.reg)));abline(0,1)



sockeye.adult.2014.reg=lm(log(Count+1)~ CT_mean+Gage_Height,data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"&Year=="2014"))

sockeye.adult.2015.reg=lm(log(Count+1)~ CT_mean+Gage_Height,data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"&Year=="2015"))

sockeye.adult.2016.reg=lm(log(Count+1)~ CT_mean+Gage_Height,data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"&Year=="2016"))

sockeye.adult.reg=lm(log(Count+1)~ CT_mean*log(Q_cfs),data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"))

summary(sockeye.adult.2014.reg)
summary(sockeye.adult.2015.reg)
summary(sockeye.adult.2016.reg)
summary(sockeye.adult.reg)


#Poisson model sockeye
sockeye.adult.2014.reg=glm((Count)~ CT_mean+Gage_Height,family="quasipoisson",,data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"&Year=="2014"))

sockeye.adult.2015.reg=glm((Count)~ CT_mean+Gage_Height,family="quasipoisson",data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"&Year=="2015"))

sockeye.adult.2016.reg=glm((Count)~ CT_mean+Gage_Height,family="quasipoisson",,data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"&Year=="2016"))

sockeye.adult.reg=lm(log(Count+1)~ CT_mean*log(Q_cfs),data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"))

summary(sockeye.adult.2014.reg)
summary(sockeye.adult.2015.reg)
summary(sockeye.adult.2016.reg)
summary(sockeye.adult.reg)



sockeye.total.2016.reg=lm(log(Count+0.1)~ CT_mean*log(Q_cfs),data=subset(sockeye_adult,Sockeyetype=="Sockeye_Total"&Year=="2016"))
summary(sockeye.total.2016.reg)


coho.adult.2014.reg=lm(log(Count+0.1)~ CT_mean*log(Q_cfs),data=subset(coho_adult,cohotype=="Coho_Adults"&Year=="2014"))
coho.adult.2015.reg=lm(log(Count+0.1)~ CT_mean*log(Q_cfs),data=subset(coho_adult,cohotype=="Coho_Adults"&Year=="2015"))
coho.adult.2016.reg=lm(log(Count+0.1)~ CT_mean*log(Q_cfs),data=subset(coho_adult,cohotype=="Coho_Adults"&Year=="2016"))
coho.adult.reg=lm(log(Count+0.1)~ CT_mean*log(Q_cfs),data=subset(coho_adult,cohotype=="Coho_Adults"))
summary(coho.adult.2014.reg)
summary(coho.adult.2015.reg)
summary(coho.adult.2016.reg)
summary(coho.adult.reg)


AIC(sockeye.adult.reg)

sockeye.adult.year.reg=lm(log(Count+1) ~ factor(Year,levels=c(2016,2014,2015))* CT_mean*(Gage_Height),data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"))
summary(sockeye.adult.year.reg) #R2=0.86
AIC(sockeye.adult.year.reg) #199.9

sockeye.adult.year.reg=lm(log(Count+1) ~ factor(Year,levels=c(2016,2014,2015))+ CT_mean*(Gage_Height),data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"))
summary(sockeye.adult.year.reg) #R2=0.82
AIC(sockeye.adult.year.reg) #205.1

sockeye.adult.year.reg=lm(log(Count+1) ~ factor(Year,levels=c(2016,2014,2015))+ CT_mean+(Gage_Height),data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"))
summary(sockeye.adult.year.reg) #R2=0.81
AIC(sockeye.adult.year.reg) #205.7

sockeye.adult.year.reg=lm(log(Count+1) ~ factor(Year,levels=c(2016,2014,2015))*(Gage_Height)+ CT_mean,data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"))
summary(sockeye.adult.year.reg) #R2=0.83
AIC(sockeye.adult.year.reg) #201.3



sockeye.adult.year2.reg=lm(log(Count+0.1)~factor(Year,levels=c(2016,2014,2015))*CT_mean*log(Q_cfs),data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"))
summary(sockeye.adult.year2.reg)
AIC(sockeye.adult.year2.reg)

sockeye.adult.year3.reg=lm(log(Count+0.1)~factor(Year,levels=c(2016,2014,2015))+CT_mean*log(Q_cfs),data=subset(sockeye_adult,Sockeyetype=="Sockeye_Adults"))
summary(sockeye.adult.year3.reg)
AIC(sockeye.adult.year3.reg)

# 
# plot(salmon_glm$Date, salmon_glm$Qcorr_qPCR, type='l')
# lines(salmon_glm$Date, exp(predict(CountvsflowDNA)), lty=2, col="blue")

```
